name: flutter_infinite_scroll_pagination
description: "This Flutter package offers effortless infinite scroll loading with just one line of wrappingâ€”no complex setup or controller needed for easy integration."
version: 1.1.1
publisher: ttankkeo112@gmail.com
repository: https://github.com/MTtankkeo/flutter_infinite_scroll_pagination
keywords:
  - infinite scroll
  - nested scroll
  - pagination
  - lazy loading
  - endless list
  - load more

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appbar: ">=1.4.5"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
